Repository knative-sandbox/async-component, pull requests merged in 2021-05, with the labels that each got.

#71 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/S

#64 Support Cloud redis
  README.md
  cmd/producer/main.go
  cmd/producer/main_test.go
  config/async/100-async-producer.yaml
  config/async/100-async-redis-source.yaml
  config/async/config-tls.yaml
Labels: approved, cla: yes, kind/documentation, kind/enhancement, lgtm, ok-to-test, size/L

#74 update with updated local gateway address
  pkg/reconciler/ingress/ingress.go
Labels: approved, cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#78 secret instead of configmap
  README.md
  cmd/producer/main.go
  config/async/100-async-producer.yaml
  config/async/config-tls.yaml
  config/async/tls-secret.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/M
