Repository knative-sandbox/async-component, pull requests merged in 2021-06, with the labels that each got.

#79 fixing capitalization to be consistent
  README.md
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#82 Update README.md
  README.md
Labels: approved, cla: yes, kind/cleanup, kind/documentation, lgtm, ok-to-test, size/S

#83 Update README.md
  README.md
Labels: approved, cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#85 Standardize aliases, use GetServiceHostName
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
Labels: approved, cla: yes, kind/cleanup, kind/enhancement, lgtm, ok-to-test, size/M
