Repository knative-sandbox/async-component, pull requests merged in 2022-11, with the labels that each got.

#116 [main] Update community files
  OWNERS_ALIASES
Labels: size/L, skip-review

#119 match eventing restructure
  test/e2e-tests.sh
Labels: kind/bug, lgtm, size/XS, approved

#118 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/L, skip-review

#117 [main] Format Go code
  cmd/producer/main.go
  cmd/producer/main_test.go
  hack/tools.go
  pkg/reconciler/ingress/ingress.go
Labels: size/M, lgtm, approved

#122 manually update hack folder
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/XL, lgtm, approved
